-- ================================================================
-- ALTA DE EMPLEADOS: áreas organizacionales + login_presets
-- Generado por scripts/generar_presets_empleados.py (73 empleados)
-- Fuente: Excel de RH "Información para Sistemas - con AREA"
-- Al primer login de cada persona, handle_new_user aplica el preset
-- (rol, área, nombre) y salta el onboarding.
-- Idempotente: ON CONFLICT DO NOTHING (no pisa presets manuales).
-- ================================================================

-- 1) Áreas (las propuestas pendientes de confirmar se ajustan en /admin)
insert into areas (nombre) values
  ('Administración y Finanzas'),
  ('Alianzas Estratégicas'),
  ('Auditoría'),
  ('Call Center'),
  ('Comercial'),
  ('Comercial (sucursales)'),
  ('Crédito'),
  ('Crédito / Control de Riesgo y Mora'),
  ('Data Science'),
  ('Dirección General'),
  ('Gente y Cultura / Comunicación'),
  ('Inversión'),
  ('Normatividad y Cumplimiento'),
  ('Operaciones'),
  ('Proyectos'),
  ('Sistemas'),
  ('Tesorería')
on conflict (nombre) do nothing;

-- 2) Presets de login (uno por empleado)
insert into login_presets (email, rol, acceso_score, area_id, nombre_completo)
values
  ('cynthia.aguilar@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Aguilar Gonzalez Cynthia Guadalupe'),
  ('adriana.alejandre@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Alejaldre Guzman Adriana'),
  ('fortino.saucedo@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito / Control de Riesgo y Mora'), 'Atilano Saucedo Fortino'),
  ('anahi.baca@financieracrediflexi.com', 'responsable', false, (select id from areas where nombre = 'Tesorería'), 'Baca Jimenez Anahi'),
  ('arturo.bautista@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Bautista Lira Arturo'),
  ('luis.barragan@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Barragán Pérez Luis Alonso'),
  ('asesor.ixtapaluca6@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Bentancourt Rojas Jacqueline'),
  ('nallely.burgos@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Burgos Martinez Nallely'),
  ('asesor.ixtapluca1@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Cabrera Flores Viridiana'),
  ('oscar.frias@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Call Center'), 'Camacho Frias Oscar Antonio'),
  ('jorge.camacho@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Call Center'), 'Camacho Gonzalez Jorge'),
  ('rodrigo.castaneda@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Castañeda Lopez Rodrigo'),
  ('ncastaneda@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Operaciones'), 'Castañeda Rodriguez Nohemi'),
  ('juan.castilla@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Castilla Galindo Juan Victor'),
  ('wanda.castro@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito'), 'Castro Dominguez Wanda Krystel'),
  ('bcerdeira@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Gente y Cultura / Comunicación'), 'Cerdeira Alvarez Benigno'),
  ('francisco.cervantes@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Administración y Finanzas'), 'Cervantes Garcia Francisco Javier'),
  ('asesor.tultitlan6@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Cruz Rendon Diana'),
  ('alejandro.cruz@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Cruz Cadena Alejandro'),
  ('asesor.puebla5@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Cuautle Pacheco Jheimy'),
  ('rolando.davila@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Proyectos'), 'Davila Monroy Rolando'),
  ('gabriela.paz@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'De Paz Dominguez Gabriela'),
  ('maria.enriquez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Call Center'), 'Enriquez Vilchis Maria Alejandra'),
  ('asesor.puebla2@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Flores Mendez Veronica'),
  ('asesor.losreyes4@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Garcia Herrera Jonathan'),
  ('eduardo.garduno@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito'), 'Garduño Castro Eduardo'),
  ('olga.gomez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito'), 'Gomez Campos Olga Janet'),
  ('jose.gomez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Gomez Solache Jose Guadalupe'),
  ('ricardo.govea@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Govea Ascencio Ricardo'),
  ('felix.gutierrez@financieracrediflexi.com', 'responsable', false, (select id from areas where nombre = 'Data Science'), 'Gutierrez Matus Felix Roberto'),
  ('brendoli.durante@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Gente y Cultura / Comunicación'), 'Hernandez Durante Brendoli'),
  ('carlos.hernandez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Hernandez Gomez Carlos Alberto'),
  ('galileo.herrera@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Administración y Finanzas'), 'Herrera Tello Joel Galileo'),
  ('mjaimes@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Jaimes Almazan Maria Isabel'),
  ('angelica.jimenez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Jimenez Garcia Angelica Maribel'),
  ('alfredo.jimenez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Auditoría'), 'Jimenez Salazar Jose Alfredo'),
  ('asesor.ixtapluca3@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Juarez Palma Ma. Ines'),
  ('ana.llamas@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Auditoría'), 'Llamas Pichardo Ana Gabriela'),
  ('asesor.losreyes3@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Lopez Cabrera Edith Alejandra'),
  ('juan.luna@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Luna Aguillon Juan Edmundo'),
  ('asesor.tultitlan5@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Martinez Gonzalez Stephanie Shantal'),
  ('carlos.mejia@financieracrediflexi.com', 'responsable', false, (select id from areas where nombre = 'Data Science'), 'Mejia Alcantara Juan Carlos'),
  ('edith.mejia@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Call Center'), 'Mejia Colin Edith'),
  ('julio.melquiades@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Sistemas'), 'Melquiades Hernandez Julio Abraham'),
  ('jose.meza@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Meza Ugalde José Ramón'),
  ('jesus.montellano@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Gente y Cultura / Comunicación'), 'Montellano Hernandez Jesus'),
  ('irvin.velazco@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Mora Velazco Irvin Uriel'),
  ('asesor.puebla1@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Olivares Morales Josue Edgar'),
  ('moises.ortega@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito / Control de Riesgo y Mora'), 'Ortega Bernal Moises'),
  ('asesor.ixtapaluca5@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Ortega Fortanel Gabriela'),
  ('heber.padilla@financieracrediflexi.com', 'responsable', false, (select id from areas where nombre = 'Tesorería'), 'Padilla Barrera Heber Jair'),
  ('alejandro.perez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Perez Delgadillo Alejandro'),
  ('hector.ramirez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Gente y Cultura / Comunicación'), 'Ramirez Ramos Agileo Hector'),
  ('yrendon@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito'), 'Rendon Diaz Yesenia'),
  ('asesor.ixtapaluca7@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Resendiz Hernandez Paula'),
  ('asesor.losreyes5@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Reyes Gonzalez Sergio'),
  ('mrios@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Rios Osorio Maritere'),
  ('ricardo.rocha@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Rocha Neria Ricardo'),
  ('jorge.rodriguez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Alianzas Estratégicas'), 'Rodriguez Du Pond Jorge Antonio'),
  ('xochitl.rosas@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Rosas Lopez Xochitl Carmen'),
  ('jesus.salazar@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Operaciones'), 'Salazar Gutierrez Jesus'),
  ('asesor.tultitlan4@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Sanchez Posada Jose Olimpo'),
  ('hector.sanchez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Crédito'), 'Sanchez Reyes Hector'),
  ('judith.serrano@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Serrano Herrera Judith Patricia'),
  ('sergio.soto@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Inversión'), 'Soto Reyes Sergio Alejandro'),
  ('dtorres@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Operaciones'), 'Torres Hernandez Diana Guadalupe'),
  ('asesor.puebla4@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial (sucursales)'), 'Troncoso Galindo Eddie Brandon'),
  ('uzziel.valdez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Data Science'), 'Valdez Ordoñez Uzziel'),
  ('dellanira.valero@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Normatividad y Cumplimiento'), 'Valero Carreño Dellanira'),
  ('jvargas@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Dirección General'), 'Vargas Castañeda Javier Jesus'),
  ('manuel.vazquez@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Sistemas'), 'Vazquez Medina Hector Manuel'),
  ('fabiola.vera@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Comercial'), 'Vera Filomeno Fabiola'),
  ('fidel.villasenor@financieracrediflexi.com', 'usuario', false, (select id from areas where nombre = 'Administración y Finanzas'), 'Villaseñor Botello Fidel')
on conflict (email) do nothing;
