create table cartera_uploads (
  id             uuid primary key default gen_random_uuid(),
  fecha_corte    date not null,
  nombre_archivo text not null,
  drive_file_id  text,
  subido_por     uuid references auth.users(id),
  estado         text not null default 'pendiente'
                 check (estado in ('pendiente','procesando','procesado','error')),
  error_detalle  text,
  rows_inserted  int,
  created_at     timestamptz default now()
);

create table stg_yunius_cartera_individual (
  id                     bigserial primary key,
  upload_id              uuid references cartera_uploads(id) on delete cascade,
  fecha_corte            date not null,
  codigo_acreditado      text not null,
  ciclo                  text not null,
  nom_region             text,
  coordinacion           text,
  codigo_promotor        text,
  nombre_promotor        text,
  codigo_recuperador     text,
  nombre_recuperador     text,
  nombre_acreditado      text,
  cod_producto           text,
  nom_producto           text,
  periodicidad           text,
  plazo_credito          smallint,
  forma_de_entrega       text,
  fecha_inicio_ciclo     date,
  fecha_fin_ciclo        date,
  cantidad_entregada     numeric(14,2),
  cantidad_prestada      numeric(14,2),
  parcialidad            numeric(12,2),
  comision_a_pagar       numeric(12,2),
  dias_mora              int,
  par_bucket             text,
  pagos_vencidos         int,
  periodos_vencidos      numeric(6,2),
  saldo_capital          numeric(14,2),
  saldo_vencido          numeric(14,2),
  saldo_capital_vencido  numeric(14,2),
  saldo_interes_vencido  numeric(14,2),
  saldo_comision_vencida numeric(14,2),
  saldo_recargos         numeric(14,2),
  saldo_total            numeric(14,2),
  saldo_adelantado       numeric(14,2),
  saldo_riesgo_capital   numeric(14,2),
  saldo_riesgo_total     numeric(14,2),
  pct_mora               numeric(6,4),
  interes_moratorio      numeric(14,2),
  monto_ultimo_pago      numeric(12,2),
  fecha_ultimo_pago      date,
  dias_desde_ultimo_pago int,
  medio_comunic_1        text,
  nombre_conyuge         text,
  telefono_conyuge       text,
  nombre_ref1 text, telefono_ref1 text,
  nombre_ref2 text, telefono_ref2 text,
  nombre_ref3 text, telefono_ref3 text,
  tipo_garantia_1        text,
  descripcion_garantia_1 text,
  garantia_1             text,
  actividad_economica_pld text,
  cod_actividad_pld      text,
  municipio              text,
  entidad_federativa     text,
  geolocalizacion        text,
  criticidad             text,
  alerta                 text,
  castigado_cartera      boolean default false,
  unique (fecha_corte, codigo_acreditado, ciclo)
);

create table loan_amortizacion_individual (
  id                   bigserial primary key,
  upload_id            uuid references cartera_uploads(id) on delete cascade,
  fecha_corte          date not null,
  codigo_acreditado    text not null,
  ciclo                text not null,
  numero_amortizacion  smallint,
  fecha_inicio         date,
  fecha_fin            date,
  fecha_limite_pago    date,
  pago_periodico       numeric(12,2),
  monto_recibido       numeric(12,2),
  monto_faltante       numeric(12,2),
  fecha_completitud    date,
  dias_mora            int,
  dias_mora_acumulados int,
  estatus              text,
  categoria            text,
  incremento           text,
  es_futura_al_corte   boolean,
  unique (fecha_corte, codigo_acreditado, ciclo, numero_amortizacion)
);

create index idx_cartera_fecha on stg_yunius_cartera_individual(fecha_corte);
create index idx_cartera_coord on stg_yunius_cartera_individual(coordinacion);
create index idx_cartera_par   on stg_yunius_cartera_individual(par_bucket);
create index idx_cartera_recup on stg_yunius_cartera_individual(codigo_recuperador);
create index idx_amort_credito on loan_amortizacion_individual(fecha_corte, codigo_acreditado);
